version: "3.8"

services:
  client:
    image: randyl78/complex-client
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: client
  api:
    image: randyl78/complex-api
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: randyl78/complex-worker
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: randyl78/complex-nginx
    hostname: nginx
    deploy:
      resources:
        limits:
          memory: 128m
    ports:
      - "80:80"
