version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'
    restart: always

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - client
      - api

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - PGPASSWORD=postgres_password
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
