  name: Deploy MultiDocker
  on:
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - uses: actions/checkout@v2

        - name: Build and test client
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-client -f ./client/Dockerfile.dev ./client
        - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/complex-client npm test

        - name: Build all services
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-client ./client
        - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-api ./server
        - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-nginx ./nginx
        - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-worker ./worker

        - name: Push service to Docker Hub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/complex-client
        - run: docker push ${{ secrets.DOCKER_USERNAME }}/complex-api
        - run: docker push ${{ secrets.DOCKER_USERNAME }}/complex-nginx
        - run: docker push ${{ secrets.DOCKER_USERNAME }}/complex-worker

        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'

        - name: Deploy to EBS
          uses: einaregilsson/beanstalk-deploy@v18
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            region: us-east-1
            version_label: ${{ github.sha }}
            application_name: multi-docker
            environment_name: Multi-docker-env
            existing_bucket_name: elasticbeanstalk-us-east-1-319633945198
            deployment_package: deploy.zip



