  name: Run tests on push
  on:
    push:
      branches:
        - '**'
        - '!main'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - uses: actions/checkout@v2
        - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-client -f ./client/Dockerfile.dev ./client
        - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/complex-client npm test
